[book]
authors = ["Simone Shawn Cazzaniga"]
language = "it"
multilingual = false
src = "src"
title = "Introduzione al Pipelining"

[output.html]
default-theme = "Ayu"
additional-js = [
    "submodules/js_builds_html/html_builders.js",
    "submodules/simple_hardware_editor_and_simulator/digitaljs_webpack_backup.js",
    "submodules/simple_hardware_editor_and_simulator/lz-string_backup.js",
    "submodules/simple_hardware_editor_and_simulator/sheas_functions.js",
    "submodules/simple_hardware_editor_and_simulator/sheas_builders.js",   
    "lesson.js"
    ]
additional-css = ["scrollbar.css", "loader.css"]
cname = "pipeline-lesson.magiwanders.com" 
